site_name: Insight Git
site_description: "Insight Git analyzes Git repositories to present comprehensive statistics."
site_author: "André F. Costa"
site_url: https://github.com/andrecosta99/ct-final

nav:
  - Home: index.md
  - API: api.md
  - Developers: dev.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.expand
    - toc.integrate
  palette:
    primary: indigo
    accent: indigo
  logo: assets/logo.png
  favicon: assets/favicon.ico

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          rendering:
            show_source: true

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
