site_name: Insight Git

nav:
  - Home: index.md
  - API: api.md
  - Functions: functions.md
  - Contributors: contributors.md
  - Developers: dev.md

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
          setup_commands:
            - import os
            - import sys
            - sys.path.append(os.path.abspath('./'))
          paths:
            - insight_git

theme:
  name: material
